name: Test

on: ['pull_request', 'push']

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --no-progress
    - name: Check coding standards
      run: composer phpcs
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --no-progress
    - name: Test the code
      run: |
        composer test
        cat ./test-coverage/coverage.txt
